In [3]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
x,y=[[0,0],[1,1],[2,2]],[0,1,2]
reg.fit([[0,0],[1,1],[2,2]],[0,1,2])
print(reg.coef_,reg.intercept_)

[0.5 0.5] 2.220446049250313e-16


In [5]:
reg=linear_model.Ridge(alpha=0.5)
reg.fit([[0,0],[1,1],[2,2]],[0,.1,1])
print(reg.coef_,reg.intercept_)

[0.22222222 0.22222222] -0.07777777777777772


In [6]:
from sklearn import linear_model
x=[[0,0],[1,1],[2,2],[3,3]]
y=[0,1,2,3]
reg=linear_model.BayesianRidge()
reg.fit(x,y)
reg.predict([[1,0]])
print(reg.coef_,reg.intercept_)

[0.49999993 0.49999993] 1.999994667656324e-07


In [10]:
from sklearn import linear_model
x,y=[[0,0],[1,1],[2,2]],[0,1,1]
clf=linear_model.LogisticRegression(solver="lbfgs")
clf.fit(x,y)
print(clf.coef_,clf.intercept_)
print(clf.predict([[0,1]]))

[[0.55547535 0.55547535]] [-0.28286781]
[1]


In [20]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
x=np.arange(6).reshape(3,2)
poly=PolynomialFeatures(degree=2)
print(poly.fit_transform(x) )
model=Pipeline([('poly',PolynomialFeatures(degree=3)),('linear',LinearRegression())])
# x=np.arange(5)
y=3-2*x+x**2
# model=model.fit(x[:,np.newaxis],y)
model=model.fit(x,y)
print(model.named_steps['linear'].coef_)
print(model.predict(x) )
# x,y

[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]
[[-7.21644966e-16 -3.34473584e-02 -3.34473584e-02 -2.47054352e-02
  -5.81527936e-02 -9.16001520e-02  1.19346256e-01  9.46408210e-02
   3.64880274e-02 -5.51121247e-02]
 [ 4.85722573e-16  2.55922970e-02  2.55922970e-02  2.64791587e-02
   5.20714557e-02  7.76637527e-02 -4.58634233e-02 -1.93842645e-02
   3.26871912e-02  1.10350944e-01]]
[[ 3.  2.]
 [ 3.  6.]
 [11. 18.]]


(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 3,  2],
        [ 3,  6],
        [11, 18]]))

In [2]:
from sklearn.kernel_ridge import KernelRidge
import numpy as np
n_samples,n_features=10,5
x,y=np.random.randn(n_samples,n_features),np.random.randn(n_samples)
clf=KernelRidge(alpha=1.0)
clf.fit(x,y).predict(x)

array([-0.65660846,  0.61070686,  0.44539645,  0.1397098 ,  0.20998279,
       -0.0651782 ,  0.18193287, -0.02559408, -0.20882512, -0.19072676])

In [3]:
from sklearn import svm
X=[[0,1],[1,1]]
y=[0,1]
clf=svm.SVC(gamma="scale",kernel='linear')
clf.fit(X,y).predict([[2,2]])
print(clf.support_vectors_,clf.support_,clf.n_support_)
print(clf.decision_function([[0,1],[1,1]]))

[[0. 1.]
 [1. 1.]] [0 1] [1 1]
[-0.93051655  0.93051655]


In [5]:
from sklearn import svm
X=[[0,0],[2,2]]
y=[0.5,2.5]
clf=svm.SVR()
clf.fit(X,y).predict([[1,1]])

array([1.5])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform([[0,20],[22,2]])
# X_train=scaler.transform(X_train)
# X_test=scaler.transform()

array([[-1.,  1.],
       [ 1., -1.]])